import { sgpyonApi } from "../../../../api/sgpyonApi";

export const getColaboradoresSgpyon = async (): Promise<any> => {
  const { data } = await sgpyonApi.get(
    `/external/CuentasPorPagar/GetColaboratorsVista/EN`
  );
  
  return data;

  /* return [
    {
      name: "test test",
      resourceTypeName: "Contractor",
      positionName: "Administration Manager",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT01",
      statusName: "Active",
      businessSectionName: "Administration",
      isCommercialName: "No",
      id: 107,
      firstName: "test 1 ",
      lastName: "test 1",
      resourceTypeId: 61,
      positionId: 88,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 115,
      email: "test1@neweratech.com",
      phone: "+1 (443) 491-5621",
      statusId: 109,
      businessSectionId: 112,
      isCommercial: false,
      countryForCalendarId: 4,
    },
    {
      name: "test test",
      resourceTypeName: "Contractor",
      positionName: "Administration Manager",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT01",
      statusName: "Active",
      businessSectionName: "Administration",
      isCommercialName: "No",
      id: 106,
      firstName: "test",
      lastName: "test",
      resourceTypeId: 61,
      positionId: 88,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 115,
      email: "test5@neseratech.com",
      phone: "+1 (443) 491-5621",
      statusId: 109,
      businessSectionId: 112,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "José Pérez",
      resourceTypeName: "Internal",
      positionName: "Other",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Heliodoro Ramos",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT01",
      statusName: "Active",
      businessSectionName: "Administration",
      isCommercialName: "No",
      id: 102,
      firstName: "José Eduardo ",
      lastName: "Pérez Hernández",
      resourceTypeId: 59,
      positionId: 91,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 1,
      manageProjects: false,
      businessProposalWorkId: 115,
      email: "Eduardo.Perez@NewEraTech.com",
      phone: "+52 (951) 270-8470",
      statusId: 109,
      businessSectionId: 112,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Ana Cruz",
      resourceTypeName: "Contractor",
      positionName: "Data Specialist",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Bench",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 101,
      firstName: "Ana",
      lastName: "Cruz",
      resourceTypeId: 61,
      positionId: 64,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Ana.Cruz@NewEraTech.com",
      phone: "",
      statusId: 122,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Camilo Rojas",
      resourceTypeName: "Contractor",
      positionName: "Data Specialist",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Jesus Revilla",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 100,
      firstName: "Camilo",
      lastName: "Rojas",
      resourceTypeId: 61,
      positionId: 64,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 65,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Camilo.Rojas@NewEraTech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Juan Cruz",
      resourceTypeName: "Contractor",
      positionName: "Project Manager",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Bench",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 99,
      firstName: "Juan Enrique",
      lastName: "Cruz Alam",
      resourceTypeId: 61,
      positionId: 78,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Juan.Cruz@NewEraTech.com",
      phone: "+52 (551) 452",
      statusId: 122,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Carlos Mercado",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Martha Soriano",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 98,
      firstName: "Carlos",
      lastName: "Mercado",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 36,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Carlos.Mercado@NewEraTech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Miriam Miranda",
      resourceTypeName: "Contractor",
      positionName: "Project Manager",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Martha Soriano",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 97,
      firstName: "Miriam ",
      lastName: "Miranda",
      resourceTypeId: 61,
      positionId: 78,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 36,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Miriam.Miranda@NewEraTech.com",
      phone: "+52 (558) 797-6380",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 17,
    },
    {
      name: "Brian Sagredo",
      resourceTypeName: "Contractor",
      positionName: "Data Specialist",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 96,
      firstName: "Brian",
      lastName: "Sagredo",
      resourceTypeId: 61,
      positionId: 64,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Brian.Sagredo@NewEraTech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Javier Barbosa",
      resourceTypeName: "Contractor",
      positionName: "Data Specialist",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Jesus Revilla",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 95,
      firstName: "Javier",
      lastName: "Barbosa",
      resourceTypeId: 61,
      positionId: 64,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 65,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Javier.Barbosa@NewEraTech.com",
      phone: "+52 (477) 755-7677",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "César Ramírez",
      resourceTypeName: "Contractor",
      positionName: "Scrum Master",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Gerardo Fernández",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 94,
      firstName: "César",
      lastName: "Ramírez",
      resourceTypeId: 61,
      positionId: 79,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 63,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "cesar.ramirez@neweratech.com",
      phone: "+52 (663) 103-5616",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 17,
    },
    {
      name: "Cristian Santillán",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Martha Soriano",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 93,
      firstName: "Cristian",
      lastName: "Santillán Rodríguez",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 36,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "cristian.santillan@neweratech.com",
      phone: "+52 (561) 856-5112",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Nydia Chávez",
      resourceTypeName: "Contractor",
      positionName: "QA Specialist",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 92,
      firstName: "Nydia",
      lastName: "Chávez Rojas",
      resourceTypeId: 61,
      positionId: 75,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "nydia.chavez@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Manuel Gutiérrez",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 91,
      firstName: "Manuel",
      lastName: "Gutiérrez Pineda",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "manuel.gutierrez@neweratech.com",
      phone: "+52 (443) 174-1091",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Paul López",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 90,
      firstName: "Paul Iván",
      lastName: "López Monreal",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "paul.lopez@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "RaChella Brookhart",
      resourceTypeName: "External",
      positionName: "Project Manager",
      isClientName: "Yes",
      clientName: "CVS",
      isManagerName: "No",
      managerName: null,
      manageProjectsName: "Yes",
      businessProposalWorkName: "ERROR",
      statusName: "Active",
      businessSectionName: "Client",
      isCommercialName: "No",
      id: 89,
      firstName: "RaChella",
      lastName: "Brookhart",
      resourceTypeId: 60,
      positionId: 78,
      isClient: true,
      clientId: 20,
      isManager: false,
      managerId: null,
      manageProjects: true,
      businessProposalWorkId: null,
      email: "rbrookhart@hogvet.com",
      phone: "",
      statusId: 109,
      businessSectionId: 114,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Vanianinetl Berzunza",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Jesus Revilla",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 88,
      firstName: "Vanianinetl",
      lastName: "Berzunza",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 65,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "vania.berzunza@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Francisco Celis",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Carlos Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 87,
      firstName: "Francisco",
      lastName: "Celis",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 58,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "francisco.celis@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Paola Rebollar",
      resourceTypeName: "Internal",
      positionName: "Infrastructure Support Engineer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 86,
      firstName: "Paola",
      lastName: "Rebollar",
      resourceTypeId: 59,
      positionId: 72,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "paola.rebollar@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Claudia Domínguez",
      resourceTypeName: "Internal",
      positionName: "Infrastructure Support Engineer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 85,
      firstName: "Claudia",
      lastName: "Domínguez",
      resourceTypeId: 59,
      positionId: 72,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "claudia.dominguez@neweratech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Manuel Guzmán",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Carlos Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 84,
      firstName: "Manuel Antonio",
      lastName: "Guzmán Ramirez",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 58,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "manuel.guzman@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Hugo Zamudio",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 83,
      firstName: "Hugo Raymundo",
      lastName: "Zamudio Rocha",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "raymundo.zamudio@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Giovanni Gualino",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 82,
      firstName: "Giovanni",
      lastName: "Gualino Alonso",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "giovanni.gualino@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Jesús Colunga",
      resourceTypeName: "Internal",
      positionName: "Applications Tester",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 81,
      firstName: "Jesús Alonso",
      lastName: "Colunga Villatoro",
      resourceTypeId: 59,
      positionId: 76,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Jesus.Colunga@NewEraTech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Paul Báez",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 80,
      firstName: "Paul",
      lastName: "Báez Ordoñez ",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Paul.Baez@NewEraTech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Thalia Zaldívar",
      resourceTypeName: "Internal",
      positionName: "Infrastructure Support Engineer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 79,
      firstName: "Thalia Regina",
      lastName: "Zaldívar Mendoza",
      resourceTypeId: 59,
      positionId: 72,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "thalia.zaldivar@neweratech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Antonio Orduño",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 78,
      firstName: "Antonio Alejandro",
      lastName: "Orduño Lopez",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "alejandro.orduno@neweratech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Luis Navarrete",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 74,
      firstName: "Luis Enrique",
      lastName: "Navarrete Puebla",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Luis.Navarrete@NewEraTech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Lorena Macias",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 73,
      firstName: "Lorena",
      lastName: "Macias Benítez",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "lorena.macias@neweratech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Pedro Lozano",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 72,
      firstName: "Pedro Armando",
      lastName: "Lozano Castillo",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Pedro.Lozano@NewEraTech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Luis Izquierdo",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 71,
      firstName: "Luis Enrique",
      lastName: "Izquierdo Guillen",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Luis.Izquierdo@NewEraTech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Florentino Hevia",
      resourceTypeName: "Internal",
      positionName: "Infrastructure Support Engineer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 70,
      firstName: "Florentino Jose",
      lastName: "Hevia García ",
      resourceTypeId: 59,
      positionId: 72,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Florentino.Hevia@NewEraTech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 17,
    },
    {
      name: "Adrian González",
      resourceTypeName: "Contractor",
      positionName: "Infrastructure Support Engineer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 69,
      firstName: "Adrian Alejandro",
      lastName: "González de León",
      resourceTypeId: 61,
      positionId: 72,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "adrian.gonzalez@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Nancy Galindo",
      resourceTypeName: "Contractor",
      positionName: "Infrastructure Support Engineer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 68,
      firstName: "Nancy",
      lastName: "Galindo Maldonado",
      resourceTypeId: 61,
      positionId: 72,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "nancy.galindo@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Diego Calzadilla",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 67,
      firstName: "Diego Antonio",
      lastName: "Calzadilla Hernández",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Diego.Calzadilla@NewEraTech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Rodrigo Vázquez",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 66,
      firstName: "Rodrigo",
      lastName: "Vázquez Villareal",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "rodrigo.vazquez@neweratech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Jesus Revilla",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "Yes",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 65,
      firstName: "Jesus Alberto",
      lastName: "Revilla Silva",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: true,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "jesus.revilla@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Mark Ilgovsky",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Bench",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 64,
      firstName: "Mark",
      lastName: "Ilgovsky Karake",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Mark.Ilgovsky@NewEraTech.com",
      phone: "",
      statusId: 122,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Gerardo Fernández",
      resourceTypeName: "Internal",
      positionName: "Infrastructure Support Engineer",
      isClientName: "No",
      clientName: null,
      isManagerName: "Yes",
      managerName: "René Castrejón",
      manageProjectsName: "Yes",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 63,
      firstName: "Gerardo Javier",
      lastName: "Fernández Sánchez ",
      resourceTypeId: 59,
      positionId: 72,
      isClient: false,
      clientId: null,
      isManager: true,
      managerId: 34,
      manageProjects: true,
      businessProposalWorkId: 117,
      email: "Gerardo.Fernandez@NewEraTech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Alexis Palacios",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Gerardo Fernández",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 62,
      firstName: "Alexis",
      lastName: "Palacios",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 63,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "alexis.palacios@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 17,
    },
    {
      name: "Satyanarayan Vaidhya",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Martha Soriano",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 61,
      firstName: "Satyanarayan",
      lastName: "Vaidhya",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 36,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "satya.vaidhya@neweratech.com",
      phone: "+52 (554) 919-3102",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 17,
    },
    {
      name: "Milton Navarro",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 60,
      firstName: "Milton",
      lastName: "Navarro",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "navarro.milton@neweratech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Pablo Cabrera",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "René Castrejón",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 59,
      firstName: "Pablo",
      lastName: "Cabrera",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 34,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "pablo.cabrera@neweratech.com",
      phone: "+52 (555) 997-4543",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Carlos Sánchez",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "Yes",
      managerName: "Heliodoro Ramos",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 58,
      firstName: "Carlos",
      lastName: "Sánchez Pérez",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: true,
      managerId: 1,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "carlos.sanchez@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Hermes Martínez",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 57,
      firstName: "Hermes Edmundo",
      lastName: "Martínez Medina",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "hermes.martinez@NewEraTech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Virgilio Bustos",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 56,
      firstName: "Virgilio Licovalí",
      lastName: "Bustos Martínez",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "virgilio.bustos@NewEraTech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Doraivelu Palanivelu",
      resourceTypeName: "External",
      positionName: "Product Owner",
      isClientName: "Yes",
      clientName: "AMCOR",
      isManagerName: "No",
      managerName: null,
      manageProjectsName: "Yes",
      businessProposalWorkName: "ERROR",
      statusName: "Active",
      businessSectionName: "Client",
      isCommercialName: "No",
      id: 55,
      firstName: "Doraivelu",
      lastName: "Palanivelu",
      resourceTypeId: 60,
      positionId: 80,
      isClient: true,
      clientId: 16,
      isManager: false,
      managerId: null,
      manageProjects: true,
      businessProposalWorkId: null,
      email: "doraivelu.palanivelu@amcor.com",
      phone: "",
      statusId: 109,
      businessSectionId: 114,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Michel Torres",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Martha Soriano",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 54,
      firstName: "Michel Giovanni",
      lastName: "Torres López",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 36,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "giovanni.torres@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 17,
    },
    {
      name: "Luis Brambila",
      resourceTypeName: "Contractor",
      positionName: "Applications Tester",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Martha Soriano",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 53,
      firstName: "Luis Carlos",
      lastName: "Brambila Ávila",
      resourceTypeId: 61,
      positionId: 76,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 36,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "luis.brambila@neweratech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Carlos Sención",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Martha Soriano",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 52,
      firstName: "Carlos Augusto",
      lastName: "Sención Morales",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 36,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "carlos.sencion@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 17,
    },
    {
      name: "Jorge Martinez",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Martha Soriano",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 51,
      firstName: "Jorge Luis",
      lastName: "Martinez Mata",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 36,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "Luis.Martinez@NewEraTech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 17,
    },
    {
      name: "José Rueda",
      resourceTypeName: "Internal",
      positionName: "Data Engineer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Martha Soriano",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 50,
      firstName: "José Antonio",
      lastName: "Rueda Balcorta",
      resourceTypeId: 59,
      positionId: 66,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 36,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "jose.rueda@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Marco Camez",
      resourceTypeName: "Contractor",
      positionName: "Data Engineer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Martha Soriano",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 49,
      firstName: "Marco Antonio",
      lastName: "Camez Chávez",
      resourceTypeId: 61,
      positionId: 66,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 36,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "marco.camez@neweratech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Diego Álvarez",
      resourceTypeName: "Contractor",
      positionName: "Data Engineer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Martha Soriano",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 48,
      firstName: "Diego Fabian",
      lastName: "Álvarez Cubillos",
      resourceTypeId: 61,
      positionId: 66,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 36,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "diego.alvarez@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 17,
    },
    {
      name: "Edgar Lopez",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 46,
      firstName: "Edgar",
      lastName: "Lopez Camacho",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "edgar.lopez@NewEraTech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Javier Encina",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 45,
      firstName: "Javier",
      lastName: "Encina",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "javier.encina@neweratech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Andres Castro",
      resourceTypeName: "Contractor",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Inactive",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 44,
      firstName: "Andres",
      lastName: "Castro",
      resourceTypeId: 61,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "andres.castro@neweratech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: null,
    },
    {
      name: "Enrique Lino",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Heliodoro Ramos",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 43,
      firstName: "Enrique",
      lastName: "Lino Camorlinga",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 1,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "enrique.lino@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Julián Molina",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 42,
      firstName: "Julián Noe",
      lastName: "Molina Gómez",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "julian.molina@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Fernando Chávez",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 41,
      firstName: "Fernando",
      lastName: "Chávez Pérez",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "fernando.chavez@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Daniel Aguilar",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 40,
      firstName: "Daniel",
      lastName: "Aguilar Avila",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "daniel.aguilar@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Romero Juan",
      resourceTypeName: "Contractor",
      positionName: "Sales Development Manager",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Erich DeJesús",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT02",
      statusName: "Active",
      businessSectionName: "Administration",
      isCommercialName: "Yes",
      id: 39,
      firstName: "Romero Avelar",
      lastName: "Juan Romero",
      resourceTypeId: 61,
      positionId: 92,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 38,
      manageProjects: false,
      businessProposalWorkId: 116,
      email: "ruben.romero@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 112,
      isCommercial: true,
      countryForCalendarId: null,
    },
    {
      name: "Erich DeJesús",
      resourceTypeName: "Internal",
      positionName: "Commercial Director",
      isClientName: "No",
      clientName: null,
      isManagerName: "Yes",
      managerName: "Heliodoro Ramos",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT01",
      statusName: "Active",
      businessSectionName: "Administration",
      isCommercialName: "Yes",
      id: 38,
      firstName: "Erich",
      lastName: "DeJesús",
      resourceTypeId: 59,
      positionId: 89,
      isClient: false,
      clientId: null,
      isManager: true,
      managerId: 1,
      manageProjects: false,
      businessProposalWorkId: 115,
      email: "hramos@aptude.com",
      phone: "",
      statusId: 109,
      businessSectionId: 112,
      isCommercial: true,
      countryForCalendarId: null,
    },
    {
      name: "Edgar Morales",
      resourceTypeName: "Internal",
      positionName: "Data Scientist",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Heliodoro Ramos",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 37,
      firstName: "Edgar Alvaro",
      lastName: "Morales Ramirez",
      resourceTypeId: 59,
      positionId: 65,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 1,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "edgar.morales@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Martha Soriano",
      resourceTypeName: "Internal",
      positionName: "Project Manager",
      isClientName: "No",
      clientName: null,
      isManagerName: "Yes",
      managerName: "Heliodoro Ramos",
      manageProjectsName: "Yes",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 36,
      firstName: "Martha Adriana",
      lastName: "Soriano Mendez",
      resourceTypeId: 59,
      positionId: 78,
      isClient: false,
      clientId: null,
      isManager: true,
      managerId: 1,
      manageProjects: true,
      businessProposalWorkId: 117,
      email: "adriana.soriano@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Astrid Sánchez",
      resourceTypeName: "Internal",
      positionName: "Project Manager",
      isClientName: "No",
      clientName: null,
      isManagerName: "Yes",
      managerName: "René Castrejón",
      manageProjectsName: "Yes",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "Yes",
      id: 35,
      firstName: "Astrid Alejandra",
      lastName: "Sánchez Mendoza",
      resourceTypeId: 59,
      positionId: 78,
      isClient: false,
      clientId: null,
      isManager: true,
      managerId: 34,
      manageProjects: true,
      businessProposalWorkId: 117,
      email: "astrid.sanchez@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: true,
      countryForCalendarId: 11,
    },
    {
      name: "René Castrejón",
      resourceTypeName: "Internal",
      positionName: "Operations Manager",
      isClientName: "No",
      clientName: null,
      isManagerName: "Yes",
      managerName: "Heliodoro Ramos",
      manageProjectsName: "Yes",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 34,
      firstName: "René Gerardo",
      lastName: "Castrejón Olvera",
      resourceTypeId: 59,
      positionId: 87,
      isClient: false,
      clientId: null,
      isManager: true,
      managerId: 1,
      manageProjects: true,
      businessProposalWorkId: 117,
      email: "rene.castrejon@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Eder Rodríguez",
      resourceTypeName: "Internal",
      positionName: "IT Talent Acquisition Agent",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Eduardo Orozco",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT01",
      statusName: "Inactive",
      businessSectionName: "Administration",
      isCommercialName: "No",
      id: 33,
      firstName: "Eder Omar",
      lastName: "Rodríguez Trejo",
      resourceTypeId: 59,
      positionId: 82,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 29,
      manageProjects: false,
      businessProposalWorkId: 115,
      email: "eder.rodriguez@neweratech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 112,
      isCommercial: false,
      countryForCalendarId: 2,
    },
    {
      name: "Raymundo García",
      resourceTypeName: "Internal",
      positionName: "IT Talent Acquisition Agent",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT01",
      statusName: "Inactive",
      businessSectionName: "Administration",
      isCommercialName: "No",
      id: 32,
      firstName: "Raymundo",
      lastName: "García Sánchez",
      resourceTypeId: 59,
      positionId: 82,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 115,
      email: "raymundo.garcia@neweratech.com",
      phone: "",
      statusId: 111,
      businessSectionId: 112,
      isCommercial: false,
      countryForCalendarId: 7,
    },
    {
      name: "Alain Green",
      resourceTypeName: "Internal",
      positionName: "IT Talent Acquisition Agent",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Eduardo Orozco",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT01",
      statusName: "Active",
      businessSectionName: "Administration",
      isCommercialName: "No",
      id: 31,
      firstName: "Alain",
      lastName: "Green Mayoral",
      resourceTypeId: 59,
      positionId: 82,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 29,
      manageProjects: false,
      businessProposalWorkId: 115,
      email: "alain.green@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 112,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Astrid Vazquez",
      resourceTypeName: "Internal",
      positionName: "IT Talent Acquisition Agent",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Eduardo Orozco",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT01",
      statusName: "Active",
      businessSectionName: "Administration",
      isCommercialName: "No",
      id: 30,
      firstName: "Astrid Desiree",
      lastName: "Vazquez Hernández",
      resourceTypeId: 59,
      positionId: 82,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 29,
      manageProjects: false,
      businessProposalWorkId: 115,
      email: "astrid.vazquez@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 112,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Eduardo Orozco",
      resourceTypeName: "Internal",
      positionName: "HR Manager",
      isClientName: "No",
      clientName: null,
      isManagerName: "Yes",
      managerName: "Heliodoro Ramos",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT01",
      statusName: "Active",
      businessSectionName: "Administration",
      isCommercialName: "No",
      id: 29,
      firstName: "Eduardo Isaac",
      lastName: "Orozco Jaén",
      resourceTypeId: 59,
      positionId: 86,
      isClient: false,
      clientId: null,
      isManager: true,
      managerId: 1,
      manageProjects: false,
      businessProposalWorkId: 115,
      email: "isaac.orozco@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 112,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Christian Alatorre",
      resourceTypeName: "Internal",
      positionName: "Sales Development Manager",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Heliodoro Ramos",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT02",
      statusName: "Active",
      businessSectionName: "Administration",
      isCommercialName: "Yes",
      id: 28,
      firstName: "Christian David",
      lastName: "Alatorre Guzmán",
      resourceTypeId: 59,
      positionId: 92,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 1,
      manageProjects: false,
      businessProposalWorkId: 116,
      email: "christian.alatorre@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 112,
      isCommercial: true,
      countryForCalendarId: 11,
    },
    {
      name: "Jesús Rodríguez",
      resourceTypeName: "Internal",
      positionName: "Sales Development Manager",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Heliodoro Ramos",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Administration",
      isCommercialName: "Yes",
      id: 27,
      firstName: "Jesús Enrique",
      lastName: "Rodríguez Ortíz",
      resourceTypeId: 59,
      positionId: 92,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 1,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "enrique.rodriguez@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 112,
      isCommercial: true,
      countryForCalendarId: 11,
    },
    {
      name: "Rodolfo Celso",
      resourceTypeName: "Internal",
      positionName: "Sales Development Manager",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Heliodoro Ramos",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT02",
      statusName: "Active",
      businessSectionName: "Administration",
      isCommercialName: "Yes",
      id: 26,
      firstName: "Rodolfo",
      lastName: "Celso Enciso",
      resourceTypeId: 59,
      positionId: 92,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 1,
      manageProjects: false,
      businessProposalWorkId: 116,
      email: "rodolfo.celso@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 112,
      isCommercial: true,
      countryForCalendarId: 11,
    },
    {
      name: "Maria Ibarra",
      resourceTypeName: "Internal",
      positionName: "Administration Manager",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Heliodoro Ramos",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT01",
      statusName: "Active",
      businessSectionName: "Administration",
      isCommercialName: "No",
      id: 25,
      firstName: "Maria Isabel",
      lastName: "Ibarra Miramar",
      resourceTypeId: 59,
      positionId: 88,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 1,
      manageProjects: false,
      businessProposalWorkId: 115,
      email: "isabel.ibarra@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 112,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Luis Nuñez",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "Yes",
      managerName: "Astrid Sánchez",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 24,
      firstName: "Luis Fernando",
      lastName: "Nuñez Delgado",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: true,
      managerId: 35,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "luis.nunez@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "Luis Urruela",
      resourceTypeName: "Internal",
      positionName: "Applications Developer",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Martha Soriano",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Operation",
      isCommercialName: "No",
      id: 10,
      firstName: "Luis",
      lastName: "Urruela",
      resourceTypeId: 59,
      positionId: 69,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 36,
      manageProjects: false,
      businessProposalWorkId: 117,
      email: "luis.urruela@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 113,
      isCommercial: false,
      countryForCalendarId: 11,
    },
    {
      name: "New Era",
      resourceTypeName: "Internal",
      positionName: "Commercial Director",
      isClientName: "No",
      clientName: null,
      isManagerName: "No",
      managerName: "Heliodoro Ramos",
      manageProjectsName: "No",
      businessProposalWorkName: "HFMT01",
      statusName: "On Hold",
      businessSectionName: "Administration",
      isCommercialName: "Yes",
      id: 7,
      firstName: "New ",
      lastName: "Era Tech Corp",
      resourceTypeId: 59,
      positionId: 89,
      isClient: false,
      clientId: null,
      isManager: false,
      managerId: 1,
      manageProjects: false,
      businessProposalWorkId: 115,
      email: "FinancialOP.us21@neweratech.com",
      phone: "",
      statusId: 110,
      businessSectionId: 112,
      isCommercial: true,
      countryForCalendarId: null,
    },
    {
      name: "Heliodoro Ramos",
      resourceTypeName: "Internal",
      positionName: "General Director",
      isClientName: "No",
      clientName: null,
      isManagerName: "Yes",
      managerName: "Heliodoro Ramos",
      manageProjectsName: "Yes",
      businessProposalWorkName: "HFMT03",
      statusName: "Active",
      businessSectionName: "Administration",
      isCommercialName: "Yes",
      id: 1,
      firstName: "Heliodoro",
      lastName: "Ramos Baltazar",
      resourceTypeId: 59,
      positionId: 90,
      isClient: false,
      clientId: null,
      isManager: true,
      managerId: 1,
      manageProjects: true,
      businessProposalWorkId: 117,
      email: "heliodoro.ramos@neweratech.com",
      phone: "",
      statusId: 109,
      businessSectionId: 112,
      isCommercial: true,
      countryForCalendarId: 11,
    },
  ]; */
};
